@host=localhost:3000

@route=api/products

###
get http://{{host}}/{{route}}

###
post http://{{host}}/{{route}}
Content-Type: application/json

{
  "id": 90,
  "title": "Rest Client Demo"
}

###
put http://{{host}}/{{route}}
Content-Type: application/json


{
  "id": 90,
  "title": "Rest Client Demo Update"
}

###
delete http://{{host}}/{{route}}
Content-Type: application/json


{
  "id": 90,
}